repository:
  description: Valian ESLint Config
  topics: eslint

  default_branch: main

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: '#cc0000'
    description: Something is broken
  - name: feature
    color: '#336699'
    description: New functionality
  - name: chore
    color: '#f2df8c'
    description: Repository or code maintenance
  - name: documentation
    color: '#6cb524'
    description: Change in the documentation

teams:
  - name: developers
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: false
        contexts:
          - Lint
      enforce_admins: true
      # Prevent merge commits from being pushed to matching branches
      required_linear_history: true
      required_signatures: true
      restrictions:
        apps: []
        users: []
        teams: []
